blank_issues_enabled: false
contact_links:
  - name: Matrix room
    url: https://matrix.to/#/#minetest-tier-mods:matrix.org
    about: Join our Matrix room to discuss new mod ideas or ask for help building them.
