# Taken and slightly modified from https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/.github/ISSUE_TEMPLATE/other.yml (MIT license).
# Thanks!
name: Other issue
description: Use this for any other issues. Do NOT create blank issues
title: "[OTHER]: "
labels: ["awaiting triage"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue.
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
